services:
  product-service:
    build:
      context: ./ProductService
    container_name: product-container
    ports:
      - "5166:8080"

  order-service:
    build:
      context: ./OrderService
    container_name: order-container
    ports:
      - "5032:8080"
    depends_on:
      - product-service
      - rabbitmq

  notification-service:
    build:
      context: ./NotificationService
    container_name: notification-container
    depends_on:
      - rabbitmq

  api-gateway:
    build:
      context: ./ApiGateway
    container_name: api-gateway-container
    ports:
      - "5142:8080"
    depends_on:
      - product-service
      - order-service

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
